[versions]

ktor = "2.3.6"
okhttp = "5.0.0-alpha.11"

koin = "3.5.0"

moko-resoures = "0.23.0"

essenty = "1.2.0"
decompose = "2.1.4"
mvikotlin = "3.3.0"

compose = "1.5.4"
compose-compiler = "1.5.4"

kotlin = "1.9.20"
kotlinx-serialization = "1.6.0"

androidx-activity = "1.8.0"

[libraries]

klock = "com.soywiz.korlibs.klock:klock:4.0.10"
napier = "io.github.aakira:napier:2.6.1"
seismic = "com.squareup:seismic:1.0.3"
reaktive = "com.badoo.reaktive:reaktive:2.0.0"

android-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }

gradle-android = "com.android.tools.build:gradle:8.1.2"
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-kotlinx-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }

coil-compose = "io.coil-kt:coil-compose:2.5.0"
lottie-compose = "com.airbnb.android:lottie-compose:6.1.0"

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

essenty-lifecycle = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-utils = { module = "io.ktor:ktor-utils", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-engine-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor"}
ktor-engine-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

moko-resources-common = { module = "dev.icerock.moko:resources", version.ref = "moko-resoures" }
moko-resources-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "moko-resoures" }
moko-resources-generator = { module = "dev.icerock.moko:resources-generator", version.ref = "moko-resoures" }

mvikotlin-rx = { module = "com.arkivanov.mvikotlin:rx", version.ref = "mvikotlin" }
mvikotlin-core = { module = "com.arkivanov.mvikotlin:mvikotlin", version.ref = "mvikotlin" }
mvikotlin-main = { module = "com.arkivanov.mvikotlin:mvikotlin-main", version.ref = "mvikotlin" }
mvikotlin-logging = { module = "com.arkivanov.mvikotlin:mvikotlin-logging", version.ref = "mvikotlin" }
mvikotlin-coroutines = { module = "com.arkivanov.mvikotlin:mvikotlin-extensions-coroutines", version.ref = "mvikotlin" }

decompose-core = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extensions-compose-jetpack = { module = "com.arkivanov.decompose:extensions-compose-jetpack", version.ref = "decompose" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-material2 = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }

[bundles]

compose = [
    "compose-ui",
    "compose-runtime",
    "compose-foundation",
    "compose-material2",
]

mvikotlin-common = [
    "mvikotlin-core",
    "mvikotlin-main",
    "mvikotlin-coroutines"
]