[versions]

ktor = "2.3.9"

koin = "3.5.3"

moko-resoures = "0.23.0"

essenty = "1.3.0"
decompose = "2.2.2"
mvikotlin = "3.3.0"

compose = "1.6.5"
compose-compiler = "1.5.11"

kotlin = "1.9.23"
kotlinx-serialization = "1.6.3"

androidx-activity = "1.8.2"

[libraries]

android-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }

coil-compose = "io.coil-kt:coil-compose:2.6.0"

gradle-android = "com.android.tools.build:gradle:8.2.2"
gradle-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-kotlinx-serialization = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-engine-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor"}
ktor-engine-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

moko-resources-common = { module = "dev.icerock.moko:resources", version.ref = "moko-resoures" }
moko-resources-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "moko-resoures" }
moko-resources-generator = { module = "dev.icerock.moko:resources-generator", version.ref = "moko-resoures" }

lottie-compose = "com.airbnb.android:lottie-compose:6.4.0"

compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-material2 = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }

essenty-lifecycle = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }

kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0"

decompose-core = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose" }
decompose-extensions-compose-jetpack = { group = "com.arkivanov.decompose", name = "extensions-compose-jetpack", version.ref = "decompose" }

mvikotlin-rx = { group = "com.arkivanov.mvikotlin", name = "rx", version.ref = "mvikotlin" }
mvikotlin-core = { group = "com.arkivanov.mvikotlin", name = "mvikotlin", version.ref = "mvikotlin" }
mvikotlin-main = { group = "com.arkivanov.mvikotlin", name = "mvikotlin-main", version.ref = "mvikotlin" }
mvikotlin-logging = { group = "com.arkivanov.mvikotlin", name = "mvikotlin-logging", version.ref = "mvikotlin" }
mvikotlin-coroutines = { group = "com.arkivanov.mvikotlin", name = "mvikotlin-extensions-coroutines", version.ref = "mvikotlin" }

napier = "io.github.aakira:napier:2.7.1"
reaktive = "com.badoo.reaktive:reaktive:2.0.1"

[bundles]

compose = [
    "compose-ui",
    "compose-runtime",
    "compose-foundation",
    "compose-material2",
]

mvikotlin-common = [
    "mvikotlin-core",
    "mvikotlin-main",
    "mvikotlin-coroutines"
]