[versions]

ktor = "2.2.2"
koin3 = "3.2.0"
okhttp = "5.0.0-alpha.10"
essenty = "0.10.0"
decompose = "1.0.0-beta-04"
mvikotlin = "3.1.0"

compose = "1.3.1"
compose-compiler = "1.4.0"
accompanist = "0.28.0"

kotlin = "1.8.0"
coroutines = "1.6.4"
kotlinx-serialization = "1.4.1"

androidx-activity = "1.6.1"

[libraries]

androidx-appcompat = "androidx.appcompat:appcompat:1.6.0"
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-core = "androidx.core:core-ktx:1.8.0"

gradle-android = "com.android.tools.build:gradle:7.4.0"
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }

compose-coil = "io.coil-kt:coil-compose:2.2.2"

okhttp-main = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

koin3-core = { module = "io.insert-koin:koin-core", version.ref = "koin3" }
koin3-android = { module = "io.insert-koin:koin-android", version.ref = "koin3" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-plugins = { module = "io.ktor:ktor-client-plugins", version.ref = "ktor" }
ktor-client-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktor"}
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-serialization-core = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }

essenty-lifecycle = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }

mvikotlin-rx = { module = "com.arkivanov.mvikotlin:rx", version.ref = "mvikotlin" }
mvikotlin-core = { module = "com.arkivanov.mvikotlin:mvikotlin", version.ref = "mvikotlin" }
mvikotlin-main = { module = "com.arkivanov.mvikotlin:mvikotlin-main", version.ref = "mvikotlin" }
mvikotlin-logging = { module = "com.arkivanov.mvikotlin:mvikotlin-logging", version.ref = "mvikotlin" }
mvikotlin-timetravel = { module = "com.arkivanov.mvikotlin:mvikotlin-timetravel", version.ref = "mvikotlin" }
mvikotlin-coroutines = { module = "com.arkivanov.mvikotlin:mvikotlin-extensions-coroutines", version.ref = "mvikotlin" }

decompose-core = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extensions-compose-jetpack = { module = "com.arkivanov.decompose:extensions-compose-jetpack", version.ref = "decompose" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-preview = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-material2 = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }

accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

[bundles]

koin3 = [
    "koin3-core",
    "koin3-android",
]

compose = [
    "compose-ui",
    "compose-preview",
    "compose-runtime",
    "compose-foundation",
    "compose-material2",
]

coroutines = [
    "kotlinx-coroutines-core",
    "kotlinx-coroutines-android"
]

decompose = [
    "decompose-core",
    "decompose-extensions-compose-jetpack"
]

mvikotlin-common = [
    "mvikotlin-core",
    "mvikotlin-main",
    "mvikotlin-coroutines"
]

mvikotlin-plugins = [
    "mvikotlin-logging",
    "mvikotlin-timetravel"
]